# Generated by Django 4.0.3 on 2022-04-03 22:39

from django.db import migrations, models
import sample.validators
import upload_validator


class Migration(migrations.Migration):

    dependencies = [
        ("sample", "0003_auto_20211014_1823"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sample",
            name="file",
            field=models.FileField(
                upload_to="uploads/",
                validators=[
                    upload_validator.FileTypeValidator(
                        allowed_types=["audio/wav", "audio/ogg", "audio/mpeg"]
                    ),
                    sample.validators.validate_pack_sample_length,
                ],
            ),
        ),
    ]
