# Generated by Django 4.0.3 on 2022-08-20 14:10

from django.db import migrations, models
import upload_validator


class Migration(migrations.Migration):

    dependencies = [
        ("sample", "0005_rename_file_sample_sample_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sample",
            name="demo",
            field=models.FileField(
                blank=True,
                upload_to="uploads/",
                validators=[
                    upload_validator.FileTypeValidator(
                        allowed_types=[
                            "audio/wav",
                            "audio/ogg",
                            "audio/mpeg",
                            "audio/x-wav",
                        ]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="sample",
            name="sample_file",
            field=models.FileField(
                upload_to="uploads/",
                validators=[
                    upload_validator.FileTypeValidator(
                        allowed_types=[
                            "audio/wav",
                            "audio/ogg",
                            "audio/mpeg",
                            "audio/x-wav",
                        ]
                    )
                ],
            ),
        ),
    ]
