# Generated by Django 4.1.3 on 2023-04-05 01:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sample", "0006_add_to_allowed_file_types"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=16)),
                (
                    "samples",
                    models.ManyToManyField(related_name="tags", to="sample.sample"),
                ),
            ],
        ),
    ]
