# Generated by Django 4.2 on 2023-04-15 22:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sample", "0007_tag"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sample",
            options={"ordering": ["id"]},
        ),
    ]
