# Generated by Django 4.2 on 2023-04-29 00:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("sample", "0008_alter_sample_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="sample",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
