# Generated by Django 4.1.3 on 2023-03-19 18:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sample", "0006_add_to_allowed_file_types"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("vote", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="vote",
            unique_together={("user", "sample")},
        ),
    ]
